# This file is available under the following license:
# under LGPL 2.1 (LICENSE.TXT) Copyright 2022 ...

FROM tomcat:9-jdk8

LABEL maintainer="..."

ARG target_app

ENV WEB_APP=${target_app}
ENV CATALINA_OPTS="-Djavax.xml.transform.TransformerFactory=net.sf.saxon.TransformerFactoryImpl"
ENV DEEGREE_WORKSPACE_ROOT=/var/lib/tomcat/.deegree

RUN groupadd -r tomcat && useradd -g tomcat -d ${CATALINA_HOME} -s /bin/bash tomcat && \
    chown -R tomcat:tomcat $CATALINA_HOME && \
    mkdir /var/lib/tomcat && \
    chown -R tomcat:tomcat /var/lib/tomcat

COPY ${WEB_APP} /tmp/${WEB_APP}
RUN chown -R tomcat:tomcat /tmp/${WEB_APP}

USER tomcat

EXPOSE 8080

# run tomcat
CMD ["catalina.sh", "run"]
