apiVersion: v1
kind: Pod
metadata:
  name: deegree3-pod
spec:
  initContainers:
  - name: deegree-init-container
    image: "docker-dev/deegree3-test-k8s-init:0.1.3"
    imagePullPolicy: IfNotPresent
    
    command: ['sh', '-c', 'cp -R /tmp/workspaces/* /root/.deegree']
    
    volumeMounts:
    - mountPath: /root/.deegree
      name: deegree3-volume
  containers:
  - name: deegree3-container-1
    image: "docker-dev/deegree3-test-k8s:0.1.4"
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080 
    volumeMounts:
    - mountPath: /root/.deegree
      name: deegree3-volume
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: deegree3-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: deegree3-secret
          key: password
    lifecycle:
      postStart:
        exec:
          command: ['/bin/sh', '-c', 'sed -i "s/DB_USER/$DB_USER/" /root/.deegree/deegree_workspace_inspire/jdbc/db.xml; sed -i "s/DB_PASSWORD/$DB_PASSWORD/" /root/.deegree/deegree_workspace_inspire/jdbc/db.xml']
  volumes:
  - name: deegree3-volume
    emptyDir: {}
    